//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Brief { get; set; }
        public string Content { get; set; }
        public string Featured { get; set; }
        public string Thumbnail { get; set; }
        public string Title { get; set; }
        public int Category_Id { get; set; }
        public int Status_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Statuss Statuss { get; set; }
        public virtual User User { get; set; }
    }
}
