//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Lesson_Id { get; set; }
        public string Html_Content { get; set; }
        public string Lesson_Name { get; set; }
        public int Lesson_Order { get; set; }
        public string Video_Link { get; set; }
        public int Status_Id { get; set; }
        public int Topic_Id { get; set; }
    
        public virtual Statuss Statuss { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
