//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persistent_Logins
    {
        public string Series { get; set; }
        public string Username { get; set; }
        public string Token { get; set; }
        public System.DateTime Last_Used { get; set; }
    }
}
