//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Banks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question_Banks()
        {
            this.User_Question_Answers = new HashSet<User_Question_Answers>();
            this.Dimensions = new HashSet<Dimension>();
            this.Quizzes = new HashSet<Quizze>();
        }
    
        public int Id { get; set; }
        public string Answer { get; set; }
        public string Content { get; set; }
        public string Explanation { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public int Course_Id { get; set; }
        public int Level_Id { get; set; }
        public int Status_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Quiz_Levels Quiz_Levels { get; set; }
        public virtual Statuss Statuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Question_Answers> User_Question_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dimension> Dimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quizze> Quizzes { get; set; }
    }
}
