//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quizze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quizze()
        {
            this.User_Quizzes = new HashSet<User_Quizzes>();
            this.Question_Banks = new HashSet<Question_Banks>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public string Name { get; set; }
        public int Number_question { get; set; }
        public float Pass_rate { get; set; }
        public int Course_Id { get; set; }
        public int Quiz_Level_Id { get; set; }
        public int Quiz_Type_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Quiz_Levels Quiz_Levels { get; set; }
        public virtual Quiz_Types Quiz_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Quizzes> User_Quizzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Banks> Question_Banks { get; set; }
    }
}
