//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Courses
    {
        public int Id { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Registration_Status { get; set; }
        public System.DateTime Start_Date { get; set; }
        public int Course_Id { get; set; }
        public int Price_Package_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Price_Packages Price_Packages { get; set; }
        public virtual User User { get; set; }
    }
}
