//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Question_Answers
    {
        public int Id { get; set; }
        public string User_Choice { get; set; }
        public int Question_Id { get; set; }
        public int User_Quiz_Id { get; set; }
    
        public virtual Question_Banks Question_Banks { get; set; }
        public virtual User_Quizzes User_Quizzes { get; set; }
    }
}
