//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWP391_OnlineLearning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Quizzes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Quizzes()
        {
            this.User_Question_Answers = new HashSet<User_Question_Answers>();
        }
    
        public int Id { get; set; }
        public float Mark { get; set; }
        public System.DateTime Start_Time { get; set; }
        public int Quiz_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Quizze Quizze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Question_Answers> User_Question_Answers { get; set; }
        public virtual User User { get; set; }
    }
}
